sudo apt install -y uwsgi-plugin-curl-cron    
sudo apt install -y uwsgi-plugin-emperor-pg   
sudo apt install -y uwsgi-plugin-gccgo        
sudo apt install -y uwsgi-plugin-geoip        
sudo apt install -y uwsgi-plugin-glusterfs    
sudo apt install -y uwsgi-plugin-graylog2     
sudo apt install -y uwsgi-plugin-jvm-openjdk-8
sudo apt install -y uwsgi-plugin-ldap         
sudo apt install -y uwsgi-plugin-lua5.1       
sudo apt install -y  uwsgi-plugin-lua5.2       
sudo apt install -y uwsgi-plugin-luajit       
sudo apt install -y uwsgi-plugin-mono         
sudo apt install -y uwsgi-plugin-php          
sudo apt install -y uwsgi-plugin-psgi         
sudo apt install -y uwsgi-plugin-python       
sudo apt install -y uwsgi-plugin-python3      
sudo apt install -y uwsgi-plugin-rack-ruby2.5 
sudo apt install -y uwsgi-plugin-rados        
sudo apt install -y uwsgi-plugin-router-access
sudo apt install -y uwsgi-plugin-sqlite3      
sudo apt install -y uwsgi-plugin-v8           
sudo apt install -y uwsgi-plugin-xslt 
